import { GetArrayInnerType } from "../../types/utils";
import { PermissionType } from "../../webapp/logic/settings";
import { DataElementDisaggregated } from "./DataElementDisaggregated";
import { DataFormTemplate } from "./DataFormTemplate";
import { Id, NamedRef, Ref } from "./ReferenceObject";

const models = ["dataSet", "program"] as const;
export type Model = GetArrayInnerType<typeof models>;
export type Models = Record<Model, boolean>;

export type OrgUnitSelectionSetting = "generation" | "import" | "both";

/* How a category option assigned to org units is matched against the selected org units:
    - "assigned": the selected org unit must itself be assigned to the category option.
    - "assignedAndDescendants": a category option assigned to an ancestor of the selected
      org unit is also included.
*/
export type CategoryOptionOrgUnitFilter = "assigned" | "assignedAndDescendants";

export type DuplicateToleranceUnit = "day" | "week" | "month" | "year";
export type DuplicateExclusion = Record<Id, Id[]>;

type DataSetId = Id;
type ProgramStageId = Id;
export type DataSetDataElementsFilter = Record<DataSetId, DataElementDisaggregated[]>;
export type ProgramStageFilter = Record<
    ProgramStageId,
    { dataElementsExcluded: Ref[]; attributesIncluded: Ref[]; externalDataElementsIncluded: Ref[] }
>;
export type ProgramStagePopulateEventsForEveryTei = Record<ProgramStageId, boolean>;

export interface AppSettings {
    models: Record<Model, boolean>;
    permissionsForGeneration: NamedRef[];
    permissionsForSettings: NamedRef[];
    permissionsForImport: NamedRef[];
    permissionsForHistory: NamedRef[];
    allPermissionsForGeneration: boolean;
    allPermissionsForSettings: boolean;
    allPermissionsForImport: boolean;
    allPermissionsForHistory: boolean;
    orgUnitSelection: OrgUnitSelectionSetting;
    categoryOptionOrgUnitFilter: CategoryOptionOrgUnitFilter;
    duplicateEnabled: boolean;
    duplicateExclusion: DuplicateExclusion;
    duplicateTolerance: number;
    duplicateToleranceUnit: DuplicateToleranceUnit;
    dataSetDataElementsFilter: DataSetDataElementsFilter;
    programStageFilter: ProgramStageFilter;
    programStagePopulateEventsForEveryTei: ProgramStagePopulateEventsForEveryTei;
    dataFormTemplate: DataFormTemplate;
    templatePermissions: TemplatePermissions;
    showAutogeneratedForms: boolean;
    showPopulateInCustomForms: boolean;
    markCompletedOnImport: boolean;
}

export type TemplatePermissions = Record<TemplateId, TemplatePermission>;

export interface TemplatePermission {
    accesses: TemplatePermissionAccess[];
    all: boolean;
}

export interface TemplatePermissionAccess extends NamedRef {
    type: PermissionType | "unknown";
}

type TemplateId = Id;
